[
    {
        "Id": 13,
		"Sku": "blackblue",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "A deep blue color with a black underglaze.",
        "DisplayName": "Small Bowl",
        "Colors": "Blue, Black"
    },
    {
        "Id": 14,
		"Sku": "goldtan",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "A white interior, half white half brown exterior bowl.",
        "DisplayName": "Small Bowl",
        "Colors": "Brown, White"
    },
    {
        "Id": 16,
		"Sku": "blackegg",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "Eggshell over a black underglaze giving off a light aqua color.",
        "DisplayName": "Small Bowl",
        "Colors": "Eggshell-Blue, Black"
    },
    {
        "Id": 17,
		"Sku": "bluedrizzelegg",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "Triple glazed; Black underglaze, blue second glaze, with eggshel finish",
        "DisplayName": "Small Bowl",
        "Colors": "Eggshell, Blue"
    },
    {
        "Id": 111,
		"Sku": "bluewhitetop",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "Eggshell over blue with a stone interior",
        "DisplayName": "Small Bowl",
        "Colors": "Eggshell, Blue, Stone"
    },
    {
        "Id": 112,
		"Sku": "celestial",
        "Type": "sm",
        "Qty": 1,
        "Price": 30,
        "Volume": "3x3in",
        "Description": "Earthy turquoise and sandalwood glazed tea cup with browned bottom finish.",
        "DisplayName": "Small Bowl",
        "Colors": "Matte Blue, Celedon, Brown"
    },
    {
        "Id": 113,
		"Sku": "oceanblue",
        "Type": "sm",
        "Qty": 3,
        "Price": 30,
        "Volume": "4x3in",
        "Description": "Browned edged mug with hint of blue covering white glaze.",
        "DisplayName": "Small Bowl",
        "Colors": "Matte Blue, Eggshell"
    },
    {
        "Id": 115,
		"Sku": "greenwhiteflat",
        "Type": "md",
        "Qty": 1,
        "Price": 35,
        "Volume": "7x2.5in",
        "Description": "Small aqua/white glazed mix as a hybrid raised plate/low raised bowl.",
        "DisplayName": "Medium Bowl",
        "Colors": "Aqua, White"
    },
    {
        "Id": 116,
		"Sku": "rustic",
        "Type": "mug",
        "Qty": 4,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "Licorice black bottom with white glazed on top creating a marshmallow brown finish.",
        "DisplayName": "Mug",
        "Colors": "Black Licorice, White"
    },
    {
        "Id": 117,
		"Sku": "blackgreen",
        "Type": "mug",
        "Qty": 4,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "Green lipped black mug with a matte exterior, glossy interior.",
        "DisplayName": "Mug",
        "Colors": "Black, Green"
    },
    {
        "Id": 118,
		"Sku": "blackwhite",
        "Type": "mug",
        "Qty": 2,
        "Price": 35,
        "Volume": "10oz",
        "Description": "White glossed matte black glaze creating a unique blue colored finish",
        "DisplayName": "Mug",
        "Colors": "Black, White"
    },
    {
        "Id": 119,
		"Sku": "rusticblue",
        "Type": "mug",
        "Qty": 3,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "Mixes of browns and blues with various looks for a cabin line feel.",
        "DisplayName": "Mug",
        "Colors": "Blue, Brown"
    },
    {
        "Id": 121,
		"Sku": "blueegg",
        "Type": "mug",
        "Qty": 2,
        "Price": 35,
        "Volume": "12oz",
        "Description": "Small blue and eggshell glazed mug.",
        "DisplayName": "Mug",
        "Colors": "Blue, Eggshell"
    },
    {
        "Id": 124,
		"Sku": "brown",
        "Type": "mug",
        "Qty": 3,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "A consistent brown colored mug with cabin-like looks.",
        "DisplayName": "Mug",
        "Colors": "Brown"
    },
    {
        "Id": 125,
		"Sku": "blueeye",
        "Type": "mug",
        "Qty": 3,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "A brown exterior, blue interior mug.",
        "DisplayName": "Mug",
        "Colors": "Brown, Blue"
    },
    {
        "Id": 126,
		"Sku": "exp",
        "Type": "mug",
        "Qty": 1,
        "Price": 35,
        "Volume": "10oz",
        "Description": "A rustic looking mug with hints of white, cream, and stone visible.",
        "DisplayName": "Mug",
        "Colors": "Brown, Stone"
    },
    {
        "Id": 127,
		"Sku": "creamwhite",
        "Type": "mug",
        "Qty": 4,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "A cream white look over the entire mug",
        "DisplayName": "Mug",
        "Colors": "Cream White"
    },
    {
        "Id": 128,
		"Sku": "stoneblue",
        "Type": "mug",
        "Qty": 5,
        "Price": 35,
        "Volume": "16oz",
        "Description": "Matte blue finish with a natural stone look.",
        "DisplayName": "Mug",
        "Colors": "Matte Blue"
    },
    {
        "Id": 129,
		"Sku": "celestial",
        "Type": "mug",
        "Qty": 4,
        "Price": 35,
        "Volume": "12-16oz",
        "Description": "Earthy turquoise and sandalwood glazed mug with browned bottom finish.",
        "DisplayName": "Mug",
        "Colors": "Matte Blue, Celedon, Brown"
    },
    {
        "Id": 130,
		"Sku": "oceanblue",
        "Type": "mug",
        "Qty": 9,
        "Price": 35,
        "Volume": "12-16oz",
        "Description": "Browned edged mug with hint of blue covering white glaze.",
        "DisplayName": "Mug",
        "Colors": "Matte Blue, Eggshell"
    },
    {
        "Id": 131,
		"Sku": "rusticwhite",
        "Type": "mug",
        "Qty": 2,
        "Price": 35,
        "Volume": "10-12oz",
        "Description": "Brown and white mix that gives off a toasted marshmallow feel.",
        "DisplayName": "Mug",
        "Colors": "White, Brown"
    },
    {
        "Id": 132,
		"Sku": "greenwhite",
        "Type": "md",
        "Qty": 1,
        "Price": 40,
        "Volume": "5x3.5in",
        "Description": "Aqua exterior/white interior glazed medium sized bowl.",
        "DisplayName": "Medium Bowl",
        "Colors": "Aqua, White"
    },
    {
        "Id": 133,
		"Sku": "bluewhite",
        "Type": "md",
        "Qty": 1,
        "Price": 40,
        "Volume": "5x3in",
        "Description": "Medium blue and white glazed mixed bowl.",
        "DisplayName": "Medium Bowl",
        "Colors": "Blue, White"
    },
    {
        "Id": 134,
		"Sku": "tri",
        "Type": "mug",
        "Qty": 4,
        "Price": 40,
        "Volume": "12-14oz",
        "Description": "Triple glazed mug with six total Colors.",
        "DisplayName": "Mug",
        "Colors": "Black Licorice, Eggshell, Blue"
    },
    {
        "Id": 135,
		"Sku": "bluestoneruby",
        "Type": "mug",
        "Qty": 2,
        "Price": 40,
        "Volume": "12oz",
        "Description": "Ruby red inside with half blue/half stone outside finish with a blue glazed handle.",
        "DisplayName": "Mug",
        "Colors": "Ruby, Blue, Stone"
    },
    {
        "Id": 136,
		"Sku": "bluewhitecurve",
        "Type": "art",
        "Qty": 1,
        "Price": 50,
        "Volume": "6x8x3.5in",
        "Description": "Folded blue and white glaze with a gray mix point.",
        "DisplayName": "Decorative Bowl",
        "Colors": "Blue, White"
    },
    {
        "Id": 137,
		"Sku": "blackgreen",
        "Type": "md",
        "Qty": 1,
        "Price": 50,
        "Volume": "7.5x3.5in",
        "Description": "Medium sized bowl with matte black exterior and a glossy green finish covering the interior.",
        "DisplayName": "Medium Bowl",
        "Colors": "Black, Green"
    },
    {
        "Id": 140,
		"Sku": "bluewhite",
        "Type": "lg",
        "Qty": 2,
        "Price": 75,
        "Volume": "8x3in",
        "Description": "Large blue and white glazed mixed bowl.",
        "DisplayName": "Large Bowl",
        "Colors": "Blue, White"
    },
    {
        "Id": 141,
		"Sku": "bluevase",
        "Type": "lg",
        "Qty": 1,
        "Price": 120,
        "Volume": "7x7x6in",
        "Description": "Large blue glaze drizzled vase.",
        "DisplayName": "Large Bowl",
        "Colors": "Blue"
    },
    {
        "Id": 142,
		"Sku": "oceanblue",
        "Type": "lg",
        "Qty": 1,
        "Price": 150,
        "Volume": "10x5in",
        "Description": "Large matte blue and eggshell white fruit bowl",
        "DisplayName": "Large Bowl",
        "Colors": "Matte Blue, Eggshell"
    }
]